apiVersion: v1
kind: Service
metadata:
  name: counter-app-service
spec:
  selector:
    app: counter-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort